### PR TITLE
KA-97, Mukhin Oleg

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by lrochka — CHANGES_REQUESTED** [review]
please squash commits into one and make sure that you did not affect others groupmates topics

**Comment by ghost** [comment]
I did the commit of 3 requests in 1. Please, check if I did it  in a proper way.

**Review by lrochka — CHANGES_REQUESTED** [review]
image
image
image

**Comment by GameOleg** [comment]
Sorry, can you help me with it? I received:

C:\Users\Oleg Think\ProjectDB\mmsa-database-systems>git reflog show
git reflog show
1db898e (HEAD) HEAD@{0}: rebase (pick): ka97, Oleg Mukhin
d64cbbe HEAD@{1}: rebase (start): checkout HEAD~4
c2a5e31 (origin/master, origin/HEAD, master) HEAD@{2}: rebase (start): checkout c2a5e31
35e61fc HEAD@{3}: rebase (skip) (squash): ka97, Oleg Mukhin
c2a5e31 (origin/master, origin/HEAD, master) HEAD@{4}: rebase (start): checkout c2a5e31
4c4f283 HEAD@{5}: rebase (continue) (squash): ka-98, Burnevska Mariana (#19)
b0f6ffc HEAD@{6}: rebase (start): checkout HEAD~3
c2a5e31 (origin/master, origin/HEAD, master) HEAD@{7}: commit: ka97, Oleg Mukhin
c21ad46 HEAD@{8}: clone: from https://github.com/GameOleg/mmsa-database-systems.git

C:\Users\Oleg Think\ProjectDB\mmsa-database-systems>git rebase -i c2a5e31
git rebase -i c2a5e31
fatal: It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
        git rebase (--continue | --abort | --skip)
If that is not the case, please
        rm -fr ".git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

So, sorry, I don't know how to fix it.

**Comment by ghost** [comment]
Sorry, sorry I am confused with squash of commits into one. May I ask you to help to solve this problem?

**Pull request closed without merging**
